# CONFIG_BT_LL_SW_LLCP_LEGACY=Y

# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
# CONFIG_BT_BUF_ACL_TX_COUNT=32
# CONFIG_BT_L2CAP_TX_BUF_COUNT=32

CONFIG_ZMK_STUDIO=Y
CONFIG_ZMK_STUDIO_LOCKING=N
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=N

CONFIG_BT_CTLR_PHY_2M=N
CONFIG_BT_CTLR_TX_PWR_PLUS_8=Y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ZMK_KEYBOARD_NAME="V&Z-Charydbis"

# 启用键盘RGB功能
CONFIG_ZMK_RGB_UNDERGLOW=Y
CONFIG_WS2812_STRIP=Y
CONFIG_LED_STRIP=Y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=Y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# 旋钮配置
CONFIG_EC11=Y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=Y

# MOUSE
CONFIG_ZMK_POINTING=Y

# Enable 32kHz crystal
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=7
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7



