CONFIG_SPI=Y

CONFIG_SPI=Y
CONFIG_INPUT=Y
CONFIG_ZMK_MOUSE=Y

CONFIG_ZMK_EXT_POWER=Y

CONFIG_PMW3610=Y
CONFIG_PMW3610_CPI=400
CONFIG_PMW3610_CPI_DIVIDOR=1
CONFIG_PMW3610_ORIENTATION_90=Y
CONFIG_PMW3610_SNIPE_CPI=200
CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=1
CONFIG_PMW3610_SCROLL_TICK=70
CONFIG_PMW3610_INVERT_X=Y

CONFIG_PMW3610_POLLING_RATE_125_SW=Y
CONFIG_PMW3610_SMART_ALGORITHM=Y

# CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=250

# CONFIG_EC11=Y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=Y
